name: storywondermobile
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  # vibrate: ^0.0.4
  # vibration: ^1.8.4
  webview_flutter: ^4.7.0
  flutter_launcher_icons: ^0.13.1
  google_nav_bar: ^5.0.6
  iconsax: ^0.0.8
  iconsax_flutter: ^1.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/story_icon.png"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

  # flutterflow: ^0.1.1
  flutterflow_ui: ^0.2.0+1
  # flutter_flow: ^0.1.1
  # flutter_test: any
  collection: '>=1.15.0 <1.19.0'
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/welcome.png
    - assets/images/send.png
    - assets/images/astronaut.png
    - assets/images/welcome2.png
    - assets/images/back.png
    - assets/images/shield.png
    - assets/images/google.png
    - assets/images/Glasses.png
    - assets/images/1.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/2.png
    - assets/images/fun.gif
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/Maven.ttf
          style: italic
    - family: myfont
      fonts:
        - asset: assets/fonts/GOTHICB0.TTF
          weight: 700
    - family: comic
      fonts: 
        - asset: assets/fonts/ComicSansMS3.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
